###redis 相关配置,不填值采用redis默认值
##redis IP地址
redis.host=127.0.0.1
  ##redis 端口
redis.port=6379
  ##redis 密码
redis.password=
  ##资源池允许最大空闲的连接数
redis.maxIdle=100
  ##资源池确保最少空闲的连接数
redis.minIdle=30
  ##资源池中最大连接数
redis.maxTotal=300
  ##连接redis超时时间(单位为毫秒)
redis.timeOut=30000
  ##当资源池连接用尽后，调用者的最大等待时间(单位为毫秒)
redis.maxWaitMillis=-1
  ##向资源池借用连接时是否做连接有效性检测(ping)，无效连接会被移除
redis.testOnBorrow=false
  ##向资源池归还连接时是否做连接有效性检测(ping)，无效连接会被移除
redis.testOnReturn=false
  ##是否开启jmx监控，可用于监控
redis.jmxEnabled=true
  ##是否开启空闲资源监测
redis.testWhileIdle=true
  ##空闲资源的检测周期(单位为毫秒)
redis.timeBetweenEvictionRunsMillis=-1
  ##资源池中资源最小空闲时间(单位为毫秒)，达到此值后空闲资源将被移除
redis.minEvictableIdleTimeMillis=
  ##做空闲资源检测时，每次的采样数,设置为-1，就是对所有连接做空闲监测
redis.numTestsPerEvictionRun=-1
  ##是否启用后进先出, 默认true
redis.lifo=true
  #密码密钥，用于密码加解密
redis.key=test
redis.database=9
